### ISSUE TITLE
!rankup is currently broken.

### ISSUE THREAD

**Issue by volcanicer** [FoggyIO/Wilfred#6] opened 2018-09-02 02:55 UTC
Using !rankup will cause Wilfred to send an "Unknown Emoji" error and not let users rankup.

**Comment by EpicShardGamingYT** [comment] 2018-09-02 06:37
You have to use client.get_emoji, not a string

**Comment by BluePhoenixGame** [comment] 2018-09-02 09:39
Im not sure what emoji you are trying to get with: `'ðŸ‘'`
But No Epic, It is possible to use an unicode Character as a emoji. Like: `👍`.

**Comment by EpicShardGamingYT** [comment] 2018-09-02 12:09
@BluePhoenixGame You have to react with a reaction object, not a string

**Comment by FoggyIO** [comment] 2018-09-02 13:31
Can Reproduce - 02/09/2018

**Comment by FoggyIO** [comment] 2018-09-02 13:33
@EpicShardGamingYT you can use a string has highlighted in documentation here: https://discordpy.readthedocs.io/en/rewrite/api.html#discord.Message.add_reaction

Note that one of the possible parameter types for Emoji is str (which is string)

It'd appear that Unicode messed something up whilst moving this over to GitHub - Will probably change it to use the actual Unicode value to be doing this with instead of the previous method of actually trying to use the char which breaks because of lack of IDE support.

**Comment by FoggyIO** [comment] 2018-09-02 14:01
Fixed applied to In-Dev branch: 7f0ecc9

Will be merged at the usual 24 hour release schedule

**Comment by FoggyIO** [comment] 2018-09-02 21:05
Fix pushed - Unconfirmed

**Comment by FoggyIO** [comment] 2018-09-02 21:08
Confirmed Fix in b87a0e2 - Closing Ticket.

**Closed by FoggyIO** 2018-09-02 21:08 UTC
Labels: Bug Report, Claimed Fix, Confirmed Bug
